#!/usr/bin/env python3
"""Convert X11 BDF bitmap fonts (width <= 8) into a C header.

Emits one `const unsigned char <name>[95][<height>]` table per font, covering
ASCII 32..126, one byte per row, MSB = leftmost pixel. Glyphs are placed into
their cell using the font bounding box baseline so descenders line up.

Usage: bdf2c.py out.h name1=path1.bdf [name2=path2.bdf ...]
"""
import sys


def parse_bdf(path):
    glyphs = {}
    fbb = None  # (w, h, xoff, yoff)
    with open(path) as f:
        lines = f.read().splitlines()
    i = 0
    enc = None
    while i < len(lines):
        parts = lines[i].split()
        if not parts:
            i += 1
            continue
        key = parts[0]
        if key == "FONTBOUNDINGBOX":
            fbb = tuple(int(v) for v in parts[1:5])
        elif key == "ENCODING":
            enc = int(parts[1])
        elif key == "BBX":
            bbx = tuple(int(v) for v in parts[1:5])
        elif key == "BITMAP":
            rows = []
            i += 1
            while lines[i].strip() != "ENDCHAR":
                rows.append(int(lines[i].strip(), 16))
                i += 1
            if enc is not None and 32 <= enc <= 255:
                glyphs[enc] = (bbx, rows)
            enc = None
        i += 1
    return fbb, glyphs


def render(fbb, glyphs, enc):
    w, h, _, yoff = fbb
    ascent = h + yoff
    cell = [0] * h
    if enc not in glyphs:
        return cell
    (bw, bh, bx, by), rows = glyphs[enc]
    top = ascent - (by + bh)
    for r, bits in enumerate(rows):
        y = top + r
        if 0 <= y < h:
            # BDF rows are left-aligned to the byte MSB; shift by x offset
            cell[y] = (bits >> bx) & 0xFF if bx >= 0 else (bits << -bx) & 0xFF
    return cell


def ascii_art(cell, w):
    return ["".join("#" if (row >> (7 - c)) & 1 else "." for c in range(w)) for row in cell]


def main():
    out_path = sys.argv[1]
    fonts = [arg.split("=", 1) for arg in sys.argv[2:]]
    out = ["// Generated by bdf2c.py — X11 misc-fixed fonts (public domain).",
           "#ifndef FONTS_H", "#define FONTS_H", ""]
    for name, path in fonts:
        fbb, glyphs = parse_bdf(path)
        w, h = fbb[0], fbb[1]
        out.append(f"#define {name.upper()}_W {w}")
        out.append(f"#define {name.upper()}_H {h}")
        out.append(f"static const unsigned char {name}[224][{h}] = {{")
        for enc in range(32, 256):
            cell = render(fbb, glyphs, enc)
            hexrow = ", ".join(f"0x{v:02x}" for v in cell)
            ch = chr(enc).replace("\\", "backslash").replace("*/", "* /") if enc < 127 else f"x{enc:02x}"
            out.append(f"  {{ {hexrow} }}, /* '{ch}' */")
        out.append("};")
        out.append("")
        # sanity print of 'A'
        print(f"--- {name} 'A' ({w}x{h}) ---")
        print("\n".join(ascii_art(render(fbb, glyphs, ord("A")), w)))
    out.append("#endif")
    with open(out_path, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
