#!/usr/bin/env python3
"""Generate the fixed 256-color palette.

Layout:
  0..31    amber ramp (hue of the design: G = 0.70*R, B = 0.156*R)
  32..247  6x6x6 RGB cube (idx = 32 + 36r + 6g + b, levels 0..5 → 0..255)
  248..255 greys

Outputs:
  palette.hex — 256 lines of RRGGBB for $readmemh
  palette.h   — C header: PAL_AMBER(i), PAL_CUBE(r,g,b), named design colors
                (each mapped to the nearest palette index)

Usage: palette_gen.py <palette.hex> <palette.h>
"""
import sys

pal = []
for i in range(32):
    r = round(255 * i / 31)
    pal.append((r, round(r * 0.71), round(r * 0.20)))
for r in range(6):
    for g in range(6):
        for b in range(6):
            pal.append((round(255 * r / 5), round(255 * g / 5), round(255 * b / 5)))
for i in range(8):
    v = 16 + i * 32
    pal.append((v, v, v))
assert len(pal) == 256

def nearest(rgb):
    r, g, b = rgb
    best, bd = 0, 1 << 30
    for i, (pr, pg, pb) in enumerate(pal):
        d = 2 * (r - pr) ** 2 + 4 * (g - pg) ** 2 + 3 * (b - pb) ** 2
        if d < bd:
            best, bd = i, d
    return best

# Design tokens (handoff README, oklch approximated as sRGB)
named = {
    "COL_BG":            (0x0B, 0x09, 0x04),  # screen background
    "COL_DRAWER_BG":     (0x12, 0x0E, 0x07),
    "COL_DIVIDER":       (0x6E, 0x4B, 0x18),  # oklch(.35 .1 55)
    "COL_ARTIST_ACTIVE": (0xF5, 0xB1, 0x4E),  # oklch(.85 .15 55)
    "COL_ARTIST_DIM":    (0x8A, 0x66, 0x33),  # oklch(.55 .1 55)
    "COL_PATH":          (0xC2, 0x8A, 0x33),  # oklch(.65 .15 55)
    "COL_TITLE":         (0xEB, 0xB5, 0x70),  # oklch(.85 .1 55)
    "COL_FOCUS":         (0xD9, 0x93, 0x2B),  # oklch(.7 .18 55)
    "COL_TRACK_TITLE":   (0xF2, 0xC2, 0x80),  # oklch(.88 .1 55)
    "COL_PLAYSTATE":     (0xC9, 0x8F, 0x40),  # oklch(.7 .15 55)
    "COL_PROGRESS_BG":   (0x47, 0x38, 0x26),  # oklch(.3 .05 55)
    "COL_CURSOR_BG":     (0x33, 0x1E, 0x0A),  # rgba(255,150,50,.15) on black
    "COL_WHITE":         (0xFF, 0xFF, 0xFF),
    "COL_BLACK":         (0x00, 0x00, 0x00),
}

hex_path, h_path = sys.argv[1], sys.argv[2]
with open(hex_path, "w") as f:
    for r, g, b in pal:
        f.write(f"{r:02x}{g:02x}{b:02x}\n")

with open(h_path, "w") as f:
    f.write("// Generated by palette_gen.py\n#ifndef PALETTE_H\n#define PALETTE_H\n\n")
    f.write("#define PAL_AMBER(i) (i)                      /* 0..31 ramp */\n")
    f.write("#define PAL_CUBE(r, g, b) (32 + 36*(r) + 6*(g) + (b)) /* 0..5 each */\n")
    f.write("#define PAL_GREY(i) (248 + (i))               /* 0..7 */\n\n")
    for name, rgb in named.items():
        i = nearest(rgb)
        f.write(f"#define {name} {i}  /* #{rgb[0]:02X}{rgb[1]:02X}{rgb[2]:02X} -> "
                f"#{pal[i][0]:02X}{pal[i][1]:02X}{pal[i][2]:02X} */\n")
    f.write("\n#endif\n")

print(f"wrote {hex_path} and {h_path}")
