#!/usr/bin/env python3
"""Generate the fixed 256-color palette.

Layout:
  0..31    amber ramp (hue of the design: G = 0.70*R, B = 0.156*R)
  32..247  6x6x6 RGB cube (idx = 32 + 36r + 6g + b, levels 0..5 → 0..255)
  248..255 greys

Outputs:
  palette.hex — 256 lines of RRGGBB for $readmemh
  palette.h   — C header: PAL_AMBER(i), PAL_CUBE(r,g,b), named design colors
                (each mapped to the nearest palette index)

Usage: palette_gen.py <palette.hex> <palette.h>
"""
import sys

pal = []
for i in range(32):
    r = round(255 * i / 31)
    pal.append((r, round(r * 0.71), round(r * 0.20)))
for r in range(6):
    for g in range(6):
        for b in range(6):
            pal.append((round(255 * r / 5), round(255 * g / 5), round(255 * b / 5)))
for i in range(8):
    v = 16 + i * 32
    pal.append((v, v, v))
assert len(pal) == 256

def nearest(rgb):
    r, g, b = rgb
    best, bd = 0, 1 << 30
    for i, (pr, pg, pb) in enumerate(pal):
        d = 2 * (r - pr) ** 2 + 4 * (g - pg) ** 2 + 3 * (b - pb) ** 2
        if d < bd:
            best, bd = i, d
    return best

def hsl(h, s, l):
    """HSL (deg, %, %) → sRGB tuple, per the design-3a token notation."""
    s /= 100.0
    l /= 100.0
    c = (1 - abs(2 * l - 1)) * s
    x = c * (1 - abs((h / 60.0) % 2 - 1))
    m = l - c / 2
    r, g, b = {0: (c, x, 0), 1: (x, c, 0), 2: (0, c, x),
               3: (0, x, c), 4: (x, 0, c), 5: (c, 0, x)}[int(h // 60) % 6]
    return tuple(round((v + m) * 255) for v in (r, g, b))

def mix(a, b, t):
    return tuple(round(a[i] + (b[i] - a[i]) * t) for i in range(3))

# Design tokens — design_handoff_pocket_tunes_3a (HSL) over the 1b oklch set.
BG        = hsl(30, 45, 8)
DRAWER_T  = hsl(28, 70, 15)   # drawer gradient top
DRAWER_B  = hsl(22, 65, 9)    # drawer gradient bottom
MBAR_T    = hsl(28, 60, 17)   # mini-bar gradient top
MBAR_B    = hsl(24, 60, 11)
named = {
    "COL_BG":            BG,
    "COL_DRAWER_BG":     mix(DRAWER_T, DRAWER_B, 0.5),   # mid — plain fills
    "COL_DIVIDER":       mix(hsl(30, 80, 45), BG, 0.6),  # hsl/0.4 alpha on bg
    "COL_ARTIST_ACTIVE": hsl(32, 90, 78),
    "COL_ARTIST_DIM":    hsl(30, 40, 55),
    "COL_PATH":          hsl(30, 90, 65),   # breadcrumb
    "COL_TITLE":         hsl(35, 85, 82),
    "COL_FOCUS":         hsl(32, 90, 55),   # focus border / progress fill kin
    # hsl(35,90,88) is a pale cream the 6x6x6 cube can't hit — its nearest
    # neighbour is pinkish #FFCCCC. Pin to the warm cream cube entry instead.
    "COL_TRACK_TITLE":   (0xFF, 0xCC, 0x99),
    "COL_PLAYSTATE":     hsl(32, 95, 60),
    "COL_PROGRESS_BG":   hsl(28, 50, 25),
    "COL_PROGRESS_FILL": hsl(32, 95, 55),
    "COL_CURSOR_BG":     mix((255, 160, 60), BG, 0.82),  # rgba(255,160,60,.18)
    "COL_SUBTITLE":      hsl(30, 55, 62),   # drawer artist·album line
    "COL_META":          hsl(30, 50, 55),   # secondary meta
    "COL_HINT":          hsl(30, 45, 48),   # footer hints
    "COL_TOGGLE_ON":     hsl(32, 95, 60),   # shuffle/repeat active
    "COL_TOGGLE_OFF":    hsl(30, 30, 42),
    "COL_CLOCK":         hsl(35, 80, 70),   # replaces the battery readout
    "COL_EQ_BG":         (0x05, 0x03, 0x01),
    "COL_EQ_HI":         hsl(45, 95, 60),   # bars >70%
    "COL_EQ_MID":        hsl(35, 95, 55),   # bars 40–70%
    "COL_EQ_LO":         hsl(22, 90, 50),   # bars <40%
    "COL_WHITE":         (0xFF, 0xFF, 0xFF),
    "COL_BLACK":         (0x00, 0x00, 0x00),
}

# Vertical gradient LUTs (top → bottom), one palette index per band.
gradients = {
    "GRAD_DRAWER":  [mix(DRAWER_T, DRAWER_B, i / 15) for i in range(16)],
    "GRAD_MINIBAR": [mix(MBAR_T, MBAR_B, i / 7) for i in range(8)],
    # warm glow over the browser background (radial approximated in bands)
    "GRAD_BG_GLOW": [mix(BG, hsl(30, 90, 30), a) for a in (0.25, 0.17, 0.10, 0.04)],
}

hex_path, h_path = sys.argv[1], sys.argv[2]
with open(hex_path, "w") as f:
    for r, g, b in pal:
        f.write(f"{r:02x}{g:02x}{b:02x}\n")

with open(h_path, "w") as f:
    f.write("// Generated by palette_gen.py\n#ifndef PALETTE_H\n#define PALETTE_H\n\n")
    f.write("#define PAL_AMBER(i) (i)                      /* 0..31 ramp */\n")
    f.write("#define PAL_CUBE(r, g, b) (32 + 36*(r) + 6*(g) + (b)) /* 0..5 each */\n")
    f.write("#define PAL_GREY(i) (248 + (i))               /* 0..7 */\n\n")
    for name, rgb in named.items():
        i = nearest(rgb)
        f.write(f"#define {name} {i}  /* #{rgb[0]:02X}{rgb[1]:02X}{rgb[2]:02X} -> "
                f"#{pal[i][0]:02X}{pal[i][1]:02X}{pal[i][2]:02X} */\n")
    f.write("\n// Vertical gradient LUTs (palette indices, top → bottom)\n")
    for name, colors in gradients.items():
        idxs = ", ".join(str(nearest(c)) for c in colors)
        f.write(f"#define {name}_N {len(colors)}\n")
        f.write(f"static const unsigned char {name}[{len(colors)}] = {{ {idxs} }};\n")
    f.write("\n#endif\n")

print(f"wrote {hex_path} and {h_path}")
