// Generated by palette_gen.py
#ifndef PALETTE_H
#define PALETTE_H

#define PAL_AMBER(i) (i)                      /* 0..31 ramp */
#define PAL_CUBE(r, g, b) (32 + 36*(r) + 6*(g) + (b)) /* 0..5 each */
#define PAL_GREY(i) (248 + (i))               /* 0..7 */

#define COL_BG 1  /* #0B0904 -> #080602 */
#define COL_DRAWER_BG 2  /* #120E07 -> #100B03 */
#define COL_DIVIDER 13  /* #6E4B18 -> #6B4C15 */
#define COL_ARTIST_ACTIVE 31  /* #F5B14E -> #FFB533 */
#define COL_ARTIST_DIM 153  /* #8A6633 -> #996633 */
#define COL_PATH 24  /* #C28A33 -> #C58C27 */
#define COL_TITLE 238  /* #EBB570 -> #FFCC66 */
#define COL_FOCUS 26  /* #D9932B -> #D6982B */
#define COL_TRACK_TITLE 239  /* #F2C280 -> #FFCC99 */
#define COL_PLAYSTATE 195  /* #C98F40 -> #CC9933 */
#define COL_PROGRESS_BG 75  /* #473826 -> #333333 */
#define COL_CURSOR_BG 6  /* #331E0A -> #31230A */
#define COL_WHITE 247  /* #FFFFFF -> #FFFFFF */
#define COL_BLACK 0  /* #000000 -> #000000 */

#endif
